apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: rps-app-monitor
  namespace: monitoring

  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: rps-app

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: http
      path: /metrics
      interval: 15s