apiVersion: v1
kind: Service

metadata:
  name: rps-service
  labels:
    app: rps-app

spec:
  type: LoadBalancer

  selector:
    app: rps-app

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000